# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# version: 2
# updates:
#   - package-ecosystem: "npm" # See documentation for possible values
#     directory: "/backend" # Location of package manifests
#     schedule:
#       interval: "weekly"
#     open-pull-requests-limit: 100
#     commit-message:
#       # Prefix all commit messages with "npm: "
#       prefix: "npm suma"
# version: 2
# updates:
#   # Enable version updates for npm
#   - package-ecosystem: "npm"
#     # Look for `package.json` and `lock` files in the `root` directory
#     directory: "/packages"
#     # Check the npm registry for updates every day (weekdays)
#     schedule:
#       interval: "daily"
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "npm frontend suma"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "npm backend suma"



